= Samora Lang Documentation
v1.0.0 - August 2023

include::content.adoc[]

[floating-title]

== Getting started

Samora Lang is simple a interpreted programing language just for educational purposes. Samora Lang was originally created by https://github.com/GraHms/[Ismael GraHms] as a fun programming language for educational purposes.

== Installation

=== Windows
You can install Samora Lang on your Windows system by running the https://github.com/obadiaspelembe/samora-lang-installers[Windows Installer] powershell script. Download the script and simply run the following command to install:

[source,cmd]
----
C:\Downloads> .\installer.ps1
----

After the installation completes you can test by simply running the following command:

[source,cmd]
----
C:\Workspace> samora hello.sml
----

=== Arch Linux
You can install Samora Lang interpreter by using the Arch user repository with the following command

[source,sh]
----
$ yay -S samora-lang 
----

== Variables 

Samora Lang variables are declared via the keyword `let`. Example:

[,go]
---- 
let name = "Samora"
----

=== Data types

Samora Lang supports primitive types like any other programming language. The following data types are supported:

* Integers
* Floats
* String
* Boolean

Variables in Samora Lang are not typed.

[,go]
----
let age = 8
let name = "Samora"
let isFast = false
----

include::footer.adoc[]
[]